### ISSUE TITLE
ERROR: Call to undefined method TYPO3\CMS\Core\Messaging\FlashMessageQueue::__call()

### ISSUE THREAD

**Issue by Minston** [dwenzel/t3events_reservation#2]
Classes/Controller/ReservationAccessTrait.php

        $flashMessageQueue = $this->getFlashMessageQueue();

        if ($flashMessageQueue instanceof FlashMessageQueue) {

            $flashMessageQueue->__call('getAllMessagesAndFlush', []);

        }

https://api.typo3.org/typo3cms/62/html/class_t_y_p_o3_1_1_c_m_s_1_1_core_1_1_messaging_1_1_flash_message_queue.html#af581fc28a714ab44d6329ee55524d44a

> Deprecated:
>     since 6.1 will be removed in 6.3

**Comment by dwenzel** [comment]
Hi @Minston,
thank you for reporting this issue and sorry for my late reply. I've been on vacation.

This was a workaround for TYPO3 6.2 (where method ´getAllMessagesAndFlush´ was protected). It is now obsolete since we do not support version 6.2 anymore and in 7.6 and 8.2 the method is public.

A fix will be included in the next version of t3events_reservation.
